# Site settings
title: Stanford Solar Decathlon 2015
email: your-email@domain.com
description: ""
baseurl: "/eden-press-site"
url: "http://awhitty.github.io/eden-press-site/"
github_username:  awhitty
# collections:
#   gallery:
#     output: true

# Build settings
markdown: kramdown
permalink: pretty
lessc: /Users/austinwhittier/.rvm/gems/ruby-2.1.0/bin/lessc
