# Site settings
title: Stanford Solar Decathlon 2015
email: your-email@domain.com
description: ""
baseurl: ""
url: "http://yourdomain.com"
github_username:  awhitty
# collections:
#   gallery:
#     output: true

# Build settings
markdown: kramdown
permalink: pretty
lessc: /Users/austinwhittier/.rvm/gems/ruby-2.1.0/bin/lessc
